---
- name: disable /etc/apt/sources.list
  file:
    path: /etc/apt/sources.list
    state: absent
  register: disabled_top_sources_list
- name: enable non-free and contrib packages
  copy:
    content: |
      # This file is managed by Ansible!
      Types: deb deb-src
      URIs: http://deb.debian.org/debian/
      Suites: bookworm
      Components: main contrib non-free
    dest: /etc/apt/sources.list.d/debian.sources
  register: deb_repo
- name: checking time of last repository refresh
  stat:
    path: /var/cache/apt/pkgcache.bin
  register: pkgcache
- name: registering last repository refresh fact
  set_fact:
    last_repository_refresh: pkgcache.mtime
    current_epoch: ansible_date_time.epoch
- name: refresh repos if needed
  when: >-
    disabled_top_sources_list.changed or
    deb_repo.changed or
    (last_repository_refresh|int < (current_epoch|int + 84000))
  apt:
    update_cache: yes
- name: install standard software
  apt:
    pkg:
      - git-core
      - gnupg2
      - pass
      - stow
      - ansible
      - tmux
      - lynx
      - rsync
      - htop
      - doc-base
      - man
      - info
      - keychain
      - strace
      - mtr
      - iperf3
      - hw-probe
      - neofetch
      - mosh
      - bc
