---
- name: include firmware.yml
  include_tasks: firmware.yml
- name: include neworking.yml
  include_tasks: networking.yml
- name: include disable-bluetooth.yml
  include_tasks: disable-bluetooth.yml
- name: include sound.yml
  include_tasks: sound.yml
